let coiffeurs = [
  {
    id: 1,
    nom: "Medoune",
    specialite: "Degrade",
    anneesExperiences: 5,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Thies",
    prestations: { Degrade: 2000, coifureSimple: 1000 },
    realisations: ["photo1.jpg", "photo2.jpg"],
  },
  {
    id: 2,
    nom: "Eva Maria",
    specialite: "Loks",
    anneesExperiences: 3,
    note: 3.7,
    aDomicile: false,
    zoneQuartier: "Diassabe",
    prestations: { Twitch: 11000, Tresse: 10000 },
    realisations: ["photo1.jpg", "photo2.jpg"],
  },
  {
    id: 3,
    nom: "Jeovany",
    specialite: "Dabala",
    anneesExperiences: 2,
    note: 2.6,
    aDomicile: true,
    zoneQuartier: "Fahu",
    prestations: { Rase: 2000, Typeu: 1000 },
    realisations: ["photo1.jpg", "photo2.jpg"],
  },
  {
    id: 4,
    nom: "Juliana",
    specialite: "Detraissage",
    anneesExperiences: 4,
    note: 4.8,
    aDomicile: false,
    zoneQuartier: "Grand Thies",
    prestations: { Loks: 2500, Simple: 1000 },
    realisations: ["photo1.jpg", "photo2.jpg"],
  },
  {
    id: 5,
    nom: "Jean Bernard",
    specialite: "Degrade Simple",
    anneesExperiences: 5,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Grand Standing",
    prestations: { Degrade: 26000, coifureSimple: 1500 },
    realisations: ["photo1.jpg", "photo2.jpg"],
  },
];

console.log(coiffeurs);
