let coiffeurs = [
  {
    id: 1,
    photo: "images/medoune.jpg",
    nom: "Medoune",
    specialite: "Degrade",
    anneesExperiences: 5,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Avenue Léopold Sédar Senghor, Thiès",
    prestations: { Degrade: 2000, coifureSimple: 1000 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "09h:00min", fin: "18h:00min" },
      mardi: { debut: "09h:00min", fin: "18h:00min" },
      mercredi: null,
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: { debut: "09h:00min", fin: "18h:00min" },
    },
    avis: [
      {
        nom: "Fatou",
        note: 5,
        commentaire: "Excellent accueil, très professionnel.",
      },
      { nom: "Mamadou", note: 4, commentaire: "Très satisfait de ma coupe." },
      { nom: "Aïcha", note: 5, commentaire: "Je recommande sans hésiter." },
    ],
    nombreAvis: 128,
    adresse: "Avenue Léopold Sédar Senghor, Thiès",
  },
  {
    id: 2,
    photo: "images/eva.jpg",
    nom: "Eva Maria",
    specialite: "Loks",
    anneesExperiences: 3,
    note: 3.7,
    aDomicile: false,
    zoneQuartier: "Thies,Diassape",
    prestations: { Twitch: 11000, Tresse: 10000 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "07h:40min", fin: "16h:40min" },
      mardi: { debut: "10h:50min", fin: "19h:00min" },
      mercredi: { debut: "12h:00min", fin: "20h:40min" },
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: null,
    },
    avis: [
      {
        nom: "Fatou",
        note: 5,
        commentaire: "Excellent accueil, très professionnel.",
      },
      { nom: "Mamadou", note: 4, commentaire: "Très satisfait de ma coupe." },
      { nom: "Aïcha", note: 5, commentaire: "Je recommande sans hésiter." },
    ],
    nombreAvis: 128,
    adress: "Thies,Diassape",
  },
  {
    id: 3,
    photo: "images/jeovany.jpg",
    nom: "Jeovany",
    specialite: "Dabala",
    anneesExperiences: 2,
    note: 2.6,
    aDomicile: true,
    zoneQuartier: "Thies,Fahu 1",
    prestations: { Rase: 2000, Typeu: 1000 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "07h:40min", fin: "16h:40min" },
      mardi: { debut: "10h:50min", fin: "19h:00min" },
      mercredi: { debut: "12h:00min", fin: "20h:40min" },
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: null,
    },
    avis: [
      {
        nom: "Fatou",
        note: 5,
        commentaire: "Excellent accueil, très professionnel.",
      },
      { nom: "Mamadou", note: 4, commentaire: "Très satisfait de ma coupe." },
      { nom: "Aïcha", note: 5, commentaire: "Je recommande sans hésiter." },
    ],
    nombreAvis: 128,
    adresse: "Thies,Fahu 1",
  },
  {
    id: 4,
    photo: "images/juliana.jpg",
    nom: "Juliana",
    specialite: "Detraissage",
    anneesExperiences: 4,
    note: 4.8,
    aDomicile: false,
    zoneQuartier: "Dakar,Parcelle",
    prestations: { Loks: 2500, Simple: 1000 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "09h:00min", fin: "18h:00min" },
      mardi: { debut: "09h:00min", fin: "18h:00min" },
      mercredi: null,
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: { debut: "09h:00min", fin: "18h:00min" },
    },
    avis: [
      {
        nom: "Fatou",
        note: 5,
        commentaire: "Excellent accueil, très professionnel.",
      },
      { nom: "Mamadou", note: 4, commentaire: "Très satisfait de ma coupe." },
      { nom: "Aïcha", note: 5, commentaire: "Je recommande sans hésiter." },
    ],
    nombreAvis: 128,
    adresse: "Dakar,Parcelle",
  },
  {
    id: 5,
    photo: "images/bernard.jpg",
    nom: "Jean Bernard",
    specialite: "Degrade Simple",
    anneesExperiences: 5,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Thies,Grand Thies",
    prestations: { Degrade: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "07h:40min", fin: "16h:40min" },
      mardi: { debut: "10h:50min", fin: "19h:00min" },
      mercredi: { debut: "12h:00min", fin: "20h:40min" },
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: null,
    },
    avis: [
      {
        nom: "Jean Arnaut",
        note: 5,
        commentaire: "Très content, je vous recomande sans hesitation",
      },
      { nom: "Mamadou", note: 2, commentaire: "Pas du tout satisfait." },
      { nom: "Jean Luc", note: 5, commentaire: "Je recommande sans hésiter." },
    ],
    nombreAvis: 128,

    adresse: "Thies,Grand Thies",
  },
  {
    id: 6,
    photo: "images/bernard.jpg",
    nom: "Angela",
    specialite: "Perruque",
    anneesExperiences: 2,
    note: 2.8,
    aDomicile: false,
    zoneQuartier: "Thies Thialy",
    prestations: { Cheveux: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "07h:40min", fin: "16h:40min" },
      mardi: { debut: "10h:50min", fin: "19h:00min" },
      mercredi: { debut: "12h:00min", fin: "20h:40min" },
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: null,
    },
    avis: [
      {
        nom: "Christine",
        note: 3.2,
        commentaire: "Excellent accueil, très professionnel.",
      },
      { nom: "Martine", note: 4, commentaire: "Très satisfait de ma coupe." },
      { nom: "Aïcha", note: 5, commentaire: "Je recommande sans hésiter." },
    ],
    nombreAvis: 128,
    adresse: "Thies Thialy",
  },
  {
    id: 7,
    photo: "images/bernard.jpg",
    nom: "Daniel",
    specialite: "Coupe",
    anneesExperiences: 3,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Thies,Grand Standing",
    prestations: { Rase: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "07h:40min", fin: "16h:40min" },
      mardi: { debut: "10h:50min", fin: "19h:00min" },
      mercredi: { debut: "12h:00min", fin: "20h:40min" },
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: null,
    },
    avis: [
      {
        nom: "Petit Joe",
        note: 4.5,
        commentaire: "Excellent accueil, très professionnel.",
      },
      {
        nom: "Mamadou",
        note: 2.5,
        commentaire: "Pas très fort mais je me plain pas non plus.",
      },
      {
        nom: "Jean Marie",
        note: 5,
        commentaire: "Je recommande sans hésiter.",
      },
    ],
    nombreAvis: 128,
    adresse: "Thies,Grand Standing",
  },
  {
    id: 8,
    photo: "images/bernard.jpg",
    nom: "Béatrice",
    specialite: "Perruque",
    anneesExperiences: 2,
    note: 2.8,
    aDomicile: false,
    zoneQuartier: "Thies,Fahu 2",
    prestations: { Cheveux: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "07h:40min", fin: "16h:40min" },
      mardi: { debut: "10h:50min", fin: "19h:00min" },
      mercredi: { debut: "12h:00min", fin: "20h:40min" },
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: null,
    },
    avis: [
      {
        nom: "Fatou",
        note: 4.5,
        commentaire: "Excellent accueil, très professionnel.",
      },
      {
        nom: "Julie",
        note: 2,
        commentaire: "Suis pas totalement satisfaites.",
      },
      { nom: "Aïcha", note: 5, commentaire: "Je recommande sans hésiter." },
    ],
    nombreAvis: 128,
    adresse: "Thies,Fahu 2",
  },
  {
    id: 9,
    photo: "images/bernard.jpg",
    nom: "Arnaud",
    specialite: "Coiffure",
    anneesExperiences: 5,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Thies,Diassape",
    prestations: { Cheveux: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "07h:40min", fin: "16h:40min" },
      mardi: { debut: "10h:50min", fin: "19h:00min" },
      mercredi: { debut: "12h:00min", fin: "20h:40min" },
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: null,
    },
    avis: [
      {
        nom: "Jean Bernard",
        note: 3.5,
        commentaire: "Pas mal  pas trop fort mais très professionnel.",
      },
      { nom: "Jeovany", note: 3, commentaire: " Satisfait de ma coupe." },
      {
        nom: "Maxim",
        note: 2,
        commentaire: "J'ai pas tellement aimé la coiffure , naz.",
      },
    ],
    nombreAvis: 163,
    adresse: "Thies,Diassape",
  },
  {
    id: 10,
    photo: "images/bernard.jpg",
    nom: "Ariana",
    specialite: "Loks",
    anneesExperiences: 4,
    note: 3.8,
    aDomicile: false,
    zoneQuartier: "Thies,Thialy",
    prestations: { Cheveux: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
    horaires: {
      lundi: { debut: "09h:00min", fin: "18h:00min" },
      mardi: { debut: "09h:00min", fin: "18h:00min" },
      mercredi: null,
      jeudi: { debut: "09h:00min", fin: "18h:00min" },
      vendredi: { debut: "09h:00min", fin: "18h:00min" },
      samedi: { debut: "09h:00min", fin: "13h:00min" },
      dimanche: { debut: "09h:00min", fin: "18h:00min" },
    },
    avis: [
      {
        nom: "Chantal",
        note: 5,
        commentaire: "Excellent accueil, très professionnel.",
      },
      {
        nom: "Maria Eva",
        note: 3,
        commentaire:
          "Suis satisfait par ma coiffure mais les employé n'étaient pas trop accueillantes",
      },
      {
        nom: "Aïcha",
        note: 4,
        commentaire: "Très professionels et je vous recommande.",
      },
    ],
    nombreAvis: 25,
    adresse: "Thies,Thialy",
  },
];
// console.log(coiffeurs);
