let coiffeurs = [
  {
    id: 1,
    photo: "images/medoune.jpg",
    nom: "Medoune",
    specialite: "Degrade",
    anneesExperiences: 5,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Thies",
    prestations: { Degrade: 2000, coifureSimple: 1000 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
  {
    id: 2,
    photo: "images/eva.jpg",
    nom: "Eva Maria",
    specialite: "Loks",
    anneesExperiences: 3,
    note: 3.7,
    aDomicile: false,
    zoneQuartier: "Diassabe",
    prestations: { Twitch: 11000, Tresse: 10000 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
  {
    id: 3,
    photo: "images/jeovany.jpg",
    nom: "Jeovany",
    specialite: "Dabala",
    anneesExperiences: 2,
    note: 2.6,
    aDomicile: true,
    zoneQuartier: "Fahu",
    prestations: { Rase: 2000, Typeu: 1000 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
  {
    id: 4,
    photo: "images/juliana.jpg",
    nom: "Juliana",
    specialite: "Detraissage",
    anneesExperiences: 4,
    note: 4.8,
    aDomicile: false,
    zoneQuartier: "Grand Thies",
    prestations: { Loks: 2500, Simple: 1000 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
  {
    id: 5,
    photo: "images/bernard.jpg",
    nom: "Jean Bernard",
    specialite: "Degrade Simple",
    anneesExperiences: 5,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Grand Standing",
    prestations: { Degrade: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
  {
    id: 6,
    photo: "images/bernard.jpg",
    nom: "Angela",
    specialite: "Perruque",
    anneesExperiences: 2,
    note: 2.8,
    aDomicile: false,
    zoneQuartier: "Thies Thialy",
    prestations: { Cheveux: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
  {
    id: 7,
    photo: "images/bernard.jpg",
    nom: "Daniel",
    specialite: "Coupe",
    anneesExperiences: 3,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Thies Parcelle",
    prestations: { Rase: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
  {
    id: 8,
    photo: "images/bernard.jpg",
    nom: "Béatrice",
    specialite: "Perruque",
    anneesExperiences: 2,
    note: 2.8,
    aDomicile: false,
    zoneQuartier: "Thies Dixième",
    prestations: { Cheveux: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
  {
    id: 9,
    photo: "images/bernard.jpg",
    nom: "Arnaud",
    specialite: "Coiffure",
    anneesExperiences: 5,
    note: 4.8,
    aDomicile: true,
    zoneQuartier: "Thies Diassabe",
    prestations: { Cheveux: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
  {
    id: 10,
    photo: "images/bernard.jpg",
    nom: "Ariana",
    specialite: "Loks",
    anneesExperiences: 4,
    note: 3.8,
    aDomicile: false,
    zoneQuartier: "Thies Grand Standing",
    prestations: { Cheveux: 26000, coifureSimple: 1500 },
    realisations: [
      "images/photo1.jpg",
      "images/photo2.jpg",
      "images/photo3.jpg",
      "images/photo4.jpg",
      "images/photo5.jpg",
    ],
  },
];
// console.log(coiffeurs);
